name: flutter_intern
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  badges: ^3.1.2
  carousel_slider: ^5.0.0
  cupertino_icons: ^1.0.2
  dartz: ^0.10.1
  firebase_core: ^3.12.1
  firebase_messaging: ^15.2.4
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.0
  flutter_local_notifications: ^18.0.1
  flutter_slidable: ^3.0.1
  flutter_svg: ^2.0.10+1
  fluttertoast: ^8.2.4
  freezed_annotation: ^2.4.1
  go_router: ^14.2.1
  google_fonts: ^6.2.1
  http: ^1.1.2
  intl: ^0.19.0
  shared_preferences: ^2.2.2
  money_formatter: ^0.0.5
  bloc: ^9.0.0
  shimmer: ^3.0.0
  date_count_down: ^3.0.0
  timezone: ^0.10.0
  flutter_widget_from_html: ^0.16.0
  flutter_staggered_grid_view: ^0.7.0
  assorted_layout_widgets: ^11.0.0
  cached_network_image: ^3.3.1
  flutter_custom_clippers: ^2.1.0
  vector_graphics_compiler: ^1.1.11+1
  vector_graphics: ^1.1.11+1
  rxdart: ^0.28.0
  equatable: ^2.0.5
  stream_transform: ^2.1.0
  meta: ^1.10.0
  infinite_scroll_pagination: ^5.0.0
  async: ^2.11.0
  google_maps_flutter: ^2.5.3
  geocoding: ^3.0.0
  location: ^7.0.1
  package_info_plus: ^8.0.0
  cloud_firestore: ^5.6.5
  bloc_concurrency: ^0.3.0
  firebase_auth: ^5.3.1
  image_picker: ^1.1.2
  dart_style: ^2.3.5

dev_dependencies:
  build_runner: ^2.4.8

  flutter_test:
    sdk: flutter
  freezed: ^2.4.6

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
flutter_gen:
  output: lib/core/assets/
  integrations:
    flutter_svg: true
# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
